export const STORE_TOKEN_AND_USER_ID = "STORE_TOKEN_AND_USER_ID";
export const CLEAR_TOKEN_AND_USER_ID = "CLEAR_TOKEN_AND_USER_ID";
export const GET_ALL_MOVIE_REVIEWS = "GET_ALL_MOVIE_REVIEWS";
export const CREATE_REVIEW_POST = "CREATE_REVIEW_POST";
export const CLEAR_REVIEWS = "CLEAR_REVIEWS";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
